### ISSUE TITLE
reportees: Some team members have 0 values for assigned/ni? and broken links.

### ISSUE THREAD

**Issue by jensstutte** [mozilla/bugzilla-dashboard#224]
Example: Jari Jalkanen, Olli Pettay, Harveer Singh, Kagami Rosylight.

**Comment by marco-c** [comment]
The issue is that their people.mozilla.org profile lists the wrong email for Bugzilla.

**Comment by marco-c** [comment]
https://github.com/mozilla/bugbot/issues/1699 will help prevent this kind of problems.

**Comment by saschanaz** [comment]
> https://github.com/mozilla/bugbot/issues/1699 will help prevent this kind of problems.

So this is for people who don't have Bugzilla entry and not really for this one, is it?

**Comment by marco-c** [comment]
As part of https://github.com/mozilla/bugbot/issues/1699 we could also detect people who have a Bugzilla email that isn't linked to any Bugzilla account.

**Comment by saschanaz** [comment]
It seems PMO has the account ID instead of email address, can the tool use the ID to fetch the current email address instead of getting the address directly from PMO (as the latter seemingly does not reflect the change in Bugzilla side)?

In the current way it'll break whenever anyone changes the address.

**Comment by saschanaz** [comment]
> As part of [mozilla/bugbot#1699](https://github.com/mozilla/bugbot/issues/1699) we could also detect people who have a Bugzilla email that isn't linked to any Bugzilla account.

I'm not sure how that would work since PMO has the account ID and technically should be always "linked" no matter how the email changes. You mean the email mismatch?

**Comment by saschanaz** [comment]
Hmm, I'd like to take a look but I don't know where this format is documented for PMO. https://github.com/mozilla/bugzilla-dashboard/blob/d3b50d02012fe9d9b5307efef4eed0fbfac0d4b1/src/static/fakeOrg.json#L11 Ideally it should not use `bugzillaEmail` directly, like here

https://github.com/mozilla/bugzilla-dashboard/blob/d3b50d02012fe9d9b5307efef4eed0fbfac0d4b1/src/views/Main/index.jsx#L117

**Comment by saschanaz** [comment]
Seems like it's from this part: https://github.com/mozilla-iam/dino-park-front-end/blob/22138104b54eba7aea621a502e3a1d9396d6a92d/src/assets/js/identities.js#L46-L64

**Comment by marco-c** [comment]
> It seems PMO has the account ID instead of email address, can the tool use the ID to fetch the current email address instead of getting the address directly from PMO (as the latter seemingly does not reflect the change in Bugzilla side)?
> 
> In the current way it'll break whenever anyone changes the address.

It might be possible, but https://github.com/mozilla/bugbot/issues/1699 has a lower implementation cost for us and should solve the problem anyway.
Another potential solution would be changing people.mozilla.org to refresh the Bugzilla email.

> > As part of [mozilla/bugbot#1699](https://github.com/mozilla/bugbot/issues/1699) we could also detect people who have a Bugzilla email that isn't linked to any Bugzilla account.
> 
> I'm not sure how that would work since PMO has the account ID and technically should be always "linked" no matter how the email changes. You mean the email mismatch?

Yes, I meant the email mismatch.

> Hmm, I'd like to take a look but I don't know where this format is documented for PMO.
> 
> https://github.com/mozilla/bugzilla-dashboard/blob/d3b50d02012fe9d9b5307efef4eed0fbfac0d4b1/src/static/fakeOrg.json#L11
> Ideally it should not use `bugzillaEmail` directly, like here
> 
> https://github.com/mozilla/bugzilla-dashboard/blob/d3b50d02012fe9d9b5307efef4eed0fbfac0d4b1/src/views/Main/index.jsx#L117

If you're interested in fixing it, we'd be happy to review a patch. The dashboard is not performing any queries, you'd need to change https://github.com/mozilla/bugzilla-dashboard-backend as well.

**Comment by marco-c** [comment]
@saschanaz I just discovered that the ID is not stable either, it can change following some account changes (e.g. merging accounts).

**Comment by saschanaz** [comment]
Oh wow, did not know merging exists, thanks.
