### ISSUE TITLE
Prototype auth + TaskCluster secrets

### ISSUE THREAD

**Issue by armenzg** [mozilla/bugzilla-dashboard#4]
We believe we can use Auth0 + TaskCluster secrets to store the org data safely.

Rail is currently looking into it and will let us know.

Kang belives the solution is safe.

This is an interim solution until CIS API v2 is ready.

**Comment by rail** [comment]
https://github.com/mozilla/bugzilla-dashboard/compare/master...rail:auth?expand=1 should be a good start point. The branch contains a lot of not required stuff (copied from my previous work) and relaxed some linter checks. I also used a different client ID (shipit's) in order to make it work locally using https://localhost:8010.

**Comment by armenzg** [comment]
**Test that we can see the secret after authenticating**
STR:
```
git checkout -b rail-auth master
git pull https://github.com/rail/bugzilla-dashboard.git auth
yarn
yarn start
```
- Open https://localhost:8010/
- Ignore the security issue: "Warning: Potential Security Risk Ahead"
- Click on "Sign in"
  - Authenticate with LDAP
  - Grant access [1]
- You can see you're authenticated [2]
- Load https://localhost:8010/test/
- Click on the button and look at the console; you will see the secret [3]

**Test that we can't see the secret without being authenticated**

- Sign out
- Click the button and the console should say 'login required'

**Test that I can'get to the secret w/o some authentication**

- Try to load this [url](https://secrets.taskcluster.net/v1/secret/garbage%2Frail%2Ftest) and get a failure message

**What's left**

- Get rid of the security warning
- Make sure we test with a secret that is restricted to staff members
  - Right now the secret's under garbage/ and it's readable by anyone
  - Who can verify this for us?
- Request a new Auth0 client or ask jabba to make changes to the one I requested
  - We would need to make it work for these hosts:
     - https://*bugzilla-management-dashboard.netlify.com/
     - http://localhost:5000/
- Upload [fake org ](https://github.com/mozilla/bugzilla-dashboard/blob/master/src/static/fakeOrg.json) data
- Change the fetching code to fetch the secret
- Review the code
- Make sure this works on Netlify

[1]
<img width="430" alt="image" src="https://user-images.githubusercontent.com/44410/50239409-17253880-0390-11e9-873f-503e7843bc2d.png">
[2]
<img width="258" alt="image" src="https://user-images.githubusercontent.com/44410/50239463-391ebb00-0390-11e9-8851-e128ea3aaa18.png">
[3]
```
{
  expires: "2019-04-21T05:24:32.321Z"
  secret: {
    foo: "bar"
  }
}
```

**Comment by armenzg** [comment]
I've rebased rail's work and I've pushed a new branch:
https://github.com/mozilla/bugzilla-dashboard/compare/rail-auth

kang mentions that the people API for IAM should be ready soon.

**Comment by armenzg** [comment]
This got completed.
We're not using CIS's people API (see [issue](https://github.com/mozilla-iam/cis/issues/402)) but TaskCluster Secrets.
