### ISSUE TITLE
Switch graphs to be line charts

### ISSUE THREAD

**Issue by armenzg** [mozilla/bugzilla-dashboard#71]
See demo:
https://www.chartjs.org/samples/latest/scales/time/financial.html

Like this:
![image](https://user-images.githubusercontent.com/44410/55962020-16b1f580-5c3e-11e9-97e9-a4dc2b9c3306.png)

instead of:
![image](https://user-images.githubusercontent.com/44410/55962029-1e719a00-5c3e-11e9-9bca-17527d25a127.png)

You will need to make changes to `ChartJsWrapper` to support this:
https://github.com/mozilla/bugzilla-dashboard/blob/00b032276debda3c4a40e715f552c831ba354b17/src/components/ChartJsWrapper/index.jsx
and probably this:
https://github.com/mozilla/bugzilla-dashboard/blob/00b032276debda3c4a40e715f552c831ba354b17/src/utils/chartJs/generateDatasetStyle.js

**Comment by sylvestre** [comment]
Looks great

**Comment by armenzg** [comment]
Switching to this:
![image](https://user-images.githubusercontent.com/44410/56049493-96f85980-5d17-11e9-9470-20238f02e546.png)
