### ISSUE TITLE
Incorrect number of needinfo (integrates old flags)

### ISSUE THREAD

**Issue by sylvestre** [mozilla/bugzilla-dashboard#94]
For example:
https://bugzilla.mozilla.org/buglist.cgi?f1=requestees.login_name&o1=equals&v1=mozillamarcia.knous%40gmail.com

It returns old and deprecated flags:

> in-moztrap | ? | marcia

**Comment by kyoshino** [comment]
I think this is the right query:

> https://bugzilla.mozilla.org/buglist.cgi?f1=requestees.login_name&o1=equals&v1=mozillamarcia.knous%40gmail.com&f2=flagtypes.name&o2=substring&v2=needinfo%3F

Once https://github.com/mozilla-bteam/bmo/pull/1156 is merged, you can:

> https://bugzilla.mozilla.org/buglist.cgi?needinfo=mozillamarcia.knous%40gmail.com
